### ISSUE TITLE
Functions exposed by the resolver aren't detected as entrypoints

### ISSUE THREAD

**Issue by jleeSeibertMedia** [atlassian-labs/FSRT#1]
Hello, I've tried to run FSRT with an app, but the run produces no output at all (debug option makes no difference). The test-apps provided with the repo seem to work fine.

The apps folder structure is:
```
project/
> node_modules/
> src/
   index.js
> web/
  index.html
manifest.yml
package.json
package-lock.json
yarn.lock 
```

The app is based on this setup: https://github.com/GerroDen/forge-sandbox

Used versions:
fsrt 0.1.0
cargo 1.65.0

Please inform me, if there is additional information I can provide for this issue.

Best regards jlee

**Comment by jwong101** [comment]
Hi, thanks for reporting this issue!
Would you mind linking the manifest.yml of the directory that you're scanning? Also, if you could provide the output of FORGE_LOG=debug fsrt [DIR] 2> ./debug.log that would be super helpful for debugging this.

Thanks!

**Comment by jleeSeibertMedia** [comment]
Hi, after talking with my team we set up a [repo](https://github.com/jleeSeibertMedia/fsrt-bug-repro-1) to reproduce the bug.

The manifest is here: https://github.com/jleeSeibertMedia/fsrt-bug-repro-1/blob/main/app/dist/manifest.yml
and the debug log is here: https://github.com/jleeSeibertMedia/fsrt-bug-repro-1/blob/main/debug2.log

**Comment by jwong101** [comment]
Ah, we're not properly detecting functions defined by the Forge resolver.
